kind: Service
apiVersion: v1
metadata:
  name: testHelidon
  labels:
    app: testHelidon
spec:
  type: ClusterIP
  selector:
    app: testHelidon
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: testHelidon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testHelidon
  template:
    metadata:
      labels:
        app: testHelidon
        version: v1
    spec:
      containers:
      - name: testHelidon
        image: testHelidon
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
